#!/bin/bash

ERRORS=`git diff --cached --name-status | awk '$1 != "R" { print $2 }' | ack '.*\.py$' | xargs pyflakes | ack '(undefined name)|(invalid syntax)'`
DIFF=`git diff -U0 --cached`
PDBS=`python .git/hooks/find_pdbs_from_diff.py "$DIFF"`
ERRORLINES=`echo "$ERRORS" | wc -l | awk '{ print $1 }'`
PDBLINES=`echo "$PDBS" | wc -l | awk '{ print $1 }'`

if [[ $ERRORLINES != 1 || $PDBLINES != 1 ]]
	then
	if [[ $ERRORLINES != 1 ]]
		then
		echo ""
		echo "Errors:"
		echo "$ERRORS"
	fi
	if [[ $PDBLINES != 1 ]]
		then
		echo ""
		echo "Found some pdb's:"
		echo "$PDBS"
	fi
	exit 1;
fi

